#!/bin/bash
#5. Is the host on the network
if [ -z "$1" ]; then
    echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
    exit 1
fi

ip_address="$1"

ping -c 5 "$ip_address" | while read -r line; do echo "$line"; done
